from textprocessingutilities import *
from guiutilities import flatten_dict
from internalstorageinterface import InternalStorageInterface

class MissionInputs(InternalStorageInterface):
    def __init__(self,
        alt_takeoff = 0,
        alt_accel = None,
        alt_climb1 = None,
        alt_cruise1 = None,
        alt_patrol1 = None,
        alt_service1 = None,
        alt_patrol2 = None,
        alt_service2 = None,
        alt_patrol3 = None,
        alt_service3 = None,
        alt_climb2 = None,
        alt_cruise2 = None,
        alt_loiter = None,
        alt_landing = 0,
        mach_takeoff = None,
        mach_accel = None,
        mach_climb1 = None,
        mach_cruise1 = None,
        mach_patrol1 = None,
        mach_service1 = None,
        mach_patrol2 = None,
        mach_service2 = None,
        mach_patrol3 = None,
        mach_service3 = None,
        mach_climb2 = None,
        mach_cruise2 = None,
        mach_loiter = None,
        dist_takeoff = None,
        dist_accel = None,
        dist_climb1 = None,
        dist_cruise1 = None,
        dist_patrol1 = None,
        dist_service1 = None,
        dist_patrol2 = None,
        dist_service2 = None,
        dist_patrol3 = None,
        dist_service3 = None,
        dist_climb2 = None,
        dist_cruise2 = None,
        dist_loiter = None,
        time_takeoff = None,
        time_accel = None,
        time_climb1 = None,
        time_cruise1 = None,
        time_patrol1 = None,
        time_service1 = None,
        time_patrol2 = None,
        time_service2 = None,
        time_patrol3 = None,
        time_service3 = None,
        time_climb2 = None,
        time_cruise2 = None,
        time_loiter = None,
        payload_takeoff = None,
        payload_accel = None,
        payload_climb1 = None,
        payload_cruise1 = None,
        payload_patrol1 = None,
        payload_service1 = None,
        payload_patrol2 = None,
        payload_service2 = None,
        payload_patrol3 = None,
        payload_service3 = None,
        payload_climb2 = None,
        payload_cruise2 = None,
        payload_loiter = None,
        exp_payload = None,
        perm_payload = None):
            self.alt_takeoff = alt_takeoff,
            self.alt_accel = alt_accel,
            self.alt_climb1 = alt_climb1,
            self.alt_cruise1 = alt_cruise1,
            self.alt_patrol1 = alt_patrol1,
            self.alt_service1 = alt_service1,
            self.alt_patrol2 = alt_patrol2,
            self.alt_service2 = alt_service2,
            self.alt_patrol3 = alt_patrol3,
            self.alt_service3 = alt_service3,
            self.alt_climb2 = alt_climb2,
            self.alt_cruise2 = alt_cruise2,
            self.alt_loiter = alt_loiter,
            self.alt_landing = alt_landing,
            self.mach_takeoff = mach_takeoff,
            self.mach_accel = mach_accel,
            self.mach_climb1 = mach_climb1,
            self.mach_cruise1 = mach_cruise1,
            self.mach_patrol1 = mach_patrol1,
            self.mach_service1 = mach_service1,
            self.mach_patrol2 = mach_patrol2,
            self.mach_service2 = mach_service2,
            self.mach_patrol3 = mach_patrol3,
            self.mach_service3 = mach_service3,
            self.mach_climb2 = mach_climb2,
            self.mach_cruise2 = mach_cruise2,
            self.mach_loiter = mach_loiter,
            self.dist_takeoff = dist_takeoff,
            self.dist_accel = dist_accel,
            self.dist_climb1 = dist_climb1,
            self.dist_cruise1 = dist_cruise1,
            self.dist_patrol1 = dist_patrol1,
            self.dist_service1 = dist_service1,
            self.dist_patrol2 = dist_patrol2,
            self.dist_service2 = dist_service2,
            self.dist_patrol3 = dist_patrol3,
            self.dist_service3 = dist_service3,
            self.dist_climb2 = dist_climb2,
            self.dist_cruise2 = dist_cruise2,
            self.dist_loiter = dist_loiter,
            self.time_takeoff = time_takeoff,
            self.time_accel = time_accel,
            self.time_climb1 = time_climb1,
            self.time_cruise1 = time_cruise1,
            self.time_patrol1 = time_patrol1,
            self.time_service1 = time_service1,
            self.time_patrol2 = time_patrol2,
            self.time_service2 = time_service2,
            self.time_patrol3 = time_patrol3,
            self.time_service3 = time_service3,
            self.time_climb2 = time_climb2,
            self.time_cruise2 = time_cruise2,
            self.time_loiter = time_loiter,
            self.payload_takeoff = payload_takeoff,
            self.payload_accel = payload_accel,
            self.payload_climb1 = payload_climb1,
            self.payload_cruise1 = payload_cruise1,
            self.payload_patrol1 = payload_patrol1,
            self.payload_service1 = payload_service1,
            self.payload_patrol2 = payload_patrol2,
            self.payload_service2 = payload_service2,
            self.payload_patrol3 = payload_patrol3,
            self.payload_service3 = payload_service3,
            self.payload_climb2 = payload_climb2,
            self.payload_cruise2 = payload_cruise2,
            self.payload_loiter = payload_loiter
            self.exp_payload = exp_payload
            self.perm_payload = perm_payload

    def pull_from_dict(self, dictionary: dict):
        flattened_dict = flatten_dict(dictionary)
        for key, value in flattened_dict.items():
            new_key = convert_from_camel_casing_to_underscores(key)
            setattr(self, new_key, to_float(value))

    def push_to_dict(self):
        dictionary = {}
        for key, value in vars(self).items():
            key1, key2 = [k.capitalize() for k in key.split('_')]
            if key1 not in dictionary:
                if key2 == "Payload":
                    dictionary[key1+key2] = value
                else:
                    dictionary[key1] = {}
                    dictionary[key1][key2] = value
            else:
                dictionary[key1][key2] = value
        return dictionary
