# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.4.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QLineEdit, QPushButton,
    QSizePolicy, QTabWidget, QWidget)

class Ui_Widget(object):
    def setupUi(self, Widget):
        if not Widget.objectName():
            Widget.setObjectName(u"Widget")
        Widget.resize(800, 600)
        self.tabWidget = QTabWidget(Widget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 801, 601))
        self.tbMain = QWidget()
        self.tbMain.setObjectName(u"tbMain")
        self.imgPlot = QLabel(self.tbMain)
        self.imgPlot.setObjectName(u"imgPlot")
        self.imgPlot.setGeometry(QRect(20, 20, 741, 471))
        self.imgPlot.setPixmap(QPixmap(u"plot_placeholder.png"))
        self.btnPlot = QPushButton(self.tbMain)
        self.btnPlot.setObjectName(u"btnPlot")
        self.btnPlot.setGeometry(QRect(350, 500, 83, 29))
        self.tabWidget.addTab(self.tbMain, "")
        self.tbBWB = QWidget()
        self.tbBWB.setObjectName(u"tbBWB")
        self.lbWingspan = QLabel(self.tbBWB)
        self.lbWingspan.setObjectName(u"lbWingspan")
        self.lbWingspan.setGeometry(QRect(10, 30, 121, 20))
        self.txtWingspan = QLineEdit(self.tbBWB)
        self.txtWingspan.setObjectName(u"txtWingspan")
        self.txtWingspan.setGeometry(QRect(140, 30, 113, 21))
        self.lbTailspan = QLabel(self.tbBWB)
        self.lbTailspan.setObjectName(u"lbTailspan")
        self.lbTailspan.setGeometry(QRect(10, 60, 121, 20))
        self.txtTailspan = QLineEdit(self.tbBWB)
        self.txtTailspan.setObjectName(u"txtTailspan")
        self.txtTailspan.setGeometry(QRect(140, 60, 113, 21))
        self.label_5 = QLabel(self.tbBWB)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 90, 121, 20))
        self.lineEdit_5 = QLineEdit(self.tbBWB)
        self.lineEdit_5.setObjectName(u"lineEdit_5")
        self.lineEdit_5.setGeometry(QRect(140, 90, 113, 21))
        self.label_6 = QLabel(self.tbBWB)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 120, 121, 20))
        self.lineEdit_6 = QLineEdit(self.tbBWB)
        self.lineEdit_6.setObjectName(u"lineEdit_6")
        self.lineEdit_6.setGeometry(QRect(140, 120, 113, 21))
        self.label_7 = QLabel(self.tbBWB)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 150, 121, 20))
        self.lineEdit_7 = QLineEdit(self.tbBWB)
        self.lineEdit_7.setObjectName(u"lineEdit_7")
        self.lineEdit_7.setGeometry(QRect(140, 150, 113, 21))
        self.label_8 = QLabel(self.tbBWB)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 180, 121, 20))
        self.lineEdit_8 = QLineEdit(self.tbBWB)
        self.lineEdit_8.setObjectName(u"lineEdit_8")
        self.lineEdit_8.setGeometry(QRect(140, 180, 113, 21))
        self.label_9 = QLabel(self.tbBWB)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(10, 210, 121, 20))
        self.lineEdit_9 = QLineEdit(self.tbBWB)
        self.lineEdit_9.setObjectName(u"lineEdit_9")
        self.lineEdit_9.setGeometry(QRect(140, 210, 113, 21))
        self.label_10 = QLabel(self.tbBWB)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(10, 240, 121, 20))
        self.lineEdit_10 = QLineEdit(self.tbBWB)
        self.lineEdit_10.setObjectName(u"lineEdit_10")
        self.lineEdit_10.setGeometry(QRect(140, 240, 113, 21))
        self.label_11 = QLabel(self.tbBWB)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(10, 270, 121, 20))
        self.lineEdit_11 = QLineEdit(self.tbBWB)
        self.lineEdit_11.setObjectName(u"lineEdit_11")
        self.lineEdit_11.setGeometry(QRect(140, 270, 113, 21))
        self.label_12 = QLabel(self.tbBWB)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(10, 300, 121, 20))
        self.lineEdit_12 = QLineEdit(self.tbBWB)
        self.lineEdit_12.setObjectName(u"lineEdit_12")
        self.lineEdit_12.setGeometry(QRect(140, 300, 113, 21))
        self.label_13 = QLabel(self.tbBWB)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(10, 330, 121, 20))
        self.lineEdit_13 = QLineEdit(self.tbBWB)
        self.lineEdit_13.setObjectName(u"lineEdit_13")
        self.lineEdit_13.setGeometry(QRect(140, 330, 113, 21))
        self.label_14 = QLabel(self.tbBWB)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(10, 360, 121, 20))
        self.lineEdit_14 = QLineEdit(self.tbBWB)
        self.lineEdit_14.setObjectName(u"lineEdit_14")
        self.lineEdit_14.setGeometry(QRect(140, 360, 113, 21))
        self.label_15 = QLabel(self.tbBWB)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(10, 390, 121, 20))
        self.lineEdit_15 = QLineEdit(self.tbBWB)
        self.lineEdit_15.setObjectName(u"lineEdit_15")
        self.lineEdit_15.setGeometry(QRect(140, 390, 113, 21))
        self.label_16 = QLabel(self.tbBWB)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(10, 420, 121, 20))
        self.lineEdit_16 = QLineEdit(self.tbBWB)
        self.lineEdit_16.setObjectName(u"lineEdit_16")
        self.lineEdit_16.setGeometry(QRect(140, 420, 113, 21))
        self.label_17 = QLabel(self.tbBWB)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(10, 450, 121, 20))
        self.lineEdit_17 = QLineEdit(self.tbBWB)
        self.lineEdit_17.setObjectName(u"lineEdit_17")
        self.lineEdit_17.setGeometry(QRect(140, 450, 113, 21))
        self.label_18 = QLabel(self.tbBWB)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(10, 480, 121, 20))
        self.lineEdit_18 = QLineEdit(self.tbBWB)
        self.lineEdit_18.setObjectName(u"lineEdit_18")
        self.lineEdit_18.setGeometry(QRect(140, 480, 113, 21))
        self.label_19 = QLabel(self.tbBWB)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(10, 510, 121, 20))
        self.lineEdit_19 = QLineEdit(self.tbBWB)
        self.lineEdit_19.setObjectName(u"lineEdit_19")
        self.lineEdit_19.setGeometry(QRect(140, 510, 113, 21))
        self.btnUpdate = QPushButton(self.tbBWB)
        self.btnUpdate.setObjectName(u"btnUpdate")
        self.btnUpdate.setGeometry(QRect(660, 30, 83, 29))
        self.tabWidget.addTab(self.tbBWB, "")
        self.tbTW = QWidget()
        self.tbTW.setObjectName(u"tbTW")
        self.tbTW.setEnabled(True)
        self.tabWidget.addTab(self.tbTW, "")

        self.retranslateUi(Widget)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(Widget)
    # setupUi

    def retranslateUi(self, Widget):
        Widget.setWindowTitle(QCoreApplication.translate("Widget", u"Widget", None))
        self.imgPlot.setText("")
        self.btnPlot.setText(QCoreApplication.translate("Widget", u"plot", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tbMain), QCoreApplication.translate("Widget", u"Main", None))
        self.lbWingspan.setText(QCoreApplication.translate("Widget", u"Wing sq ft:", None))
        self.lbTailspan.setText(QCoreApplication.translate("Widget", u"Vertical Tail sq ft:", None))
        self.label_5.setText(QCoreApplication.translate("Widget", u"Wingspan:", None))
        self.label_6.setText(QCoreApplication.translate("Widget", u"Wingspan:", None))
        self.label_7.setText(QCoreApplication.translate("Widget", u"Wingspan:", None))
        self.label_8.setText(QCoreApplication.translate("Widget", u"Wingspan:", None))
        self.label_9.setText(QCoreApplication.translate("Widget", u"Wingspan:", None))
        self.label_10.setText(QCoreApplication.translate("Widget", u"Wingspan:", None))
        self.label_11.setText(QCoreApplication.translate("Widget", u"Wingspan:", None))
        self.label_12.setText(QCoreApplication.translate("Widget", u"Wingspan:", None))
        self.label_13.setText(QCoreApplication.translate("Widget", u"Wingspan:", None))
        self.label_14.setText(QCoreApplication.translate("Widget", u"Wingspan:", None))
        self.label_15.setText(QCoreApplication.translate("Widget", u"Wingspan:", None))
        self.label_16.setText(QCoreApplication.translate("Widget", u"Wingspan:", None))
        self.label_17.setText(QCoreApplication.translate("Widget", u"Wingspan:", None))
        self.label_18.setText(QCoreApplication.translate("Widget", u"Wingspan:", None))
        self.label_19.setText(QCoreApplication.translate("Widget", u"Wingspan:", None))
        self.btnUpdate.setText(QCoreApplication.translate("Widget", u"Update", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tbBWB), QCoreApplication.translate("Widget", u"BWB", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tbTW), QCoreApplication.translate("Widget", u"Tube And Wing", None))
    # retranslateUi

