# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.4.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QLineEdit, QListWidget,
    QListWidgetItem, QPushButton, QSizePolicy, QTabWidget,
    QTextBrowser, QWidget)

class Ui_Widget(object):
    def setupUi(self, Widget):
        if not Widget.objectName():
            Widget.setObjectName(u"Widget")
        Widget.resize(800, 600)
        self.tabWidget = QTabWidget(Widget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 801, 601))
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.addButton = QPushButton(self.tab)
        self.addButton.setObjectName(u"addButton")
        self.addButton.setGeometry(QRect(440, 20, 93, 29))
        self.lineEdit = QLineEdit(self.tab)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(20, 20, 113, 26))
        self.lineEdit_2 = QLineEdit(self.tab)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(170, 20, 113, 26))
        self.textBrowser = QTextBrowser(self.tab)
        self.textBrowser.setObjectName(u"textBrowser")
        self.textBrowser.setGeometry(QRect(320, 20, 111, 31))
        self.label = QLabel(self.tab)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(150, 20, 21, 20))
        self.label_2 = QLabel(self.tab)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(300, 20, 21, 20))
        self.imgPlot = QLabel(self.tab)
        self.imgPlot.setObjectName(u"imgPlot")
        self.imgPlot.setGeometry(QRect(20, 60, 301, 271))
        self.imgPlot.setPixmap(QPixmap(u"plot_placeholder.png"))
        self.btnPlot = QPushButton(self.tab)
        self.btnPlot.setObjectName(u"btnPlot")
        self.btnPlot.setGeometry(QRect(120, 340, 83, 29))
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.insertButton = QPushButton(self.tab_2)
        self.insertButton.setObjectName(u"insertButton")
        self.insertButton.setGeometry(QRect(40, 80, 161, 29))
        self.btnVSP = QPushButton(self.tab_2)
        self.btnVSP.setObjectName(u"btnVSP")
        self.btnVSP.setGeometry(QRect(40, 190, 161, 29))
        self.txtScale = QLineEdit(self.tab_2)
        self.txtScale.setObjectName(u"txtScale")
        self.txtScale.setGeometry(QRect(40, 150, 161, 28))
        self.lst_excel = QListWidget(self.tab_2)
        QListWidgetItem(self.lst_excel)
        QListWidgetItem(self.lst_excel)
        QListWidgetItem(self.lst_excel)
        QListWidgetItem(self.lst_excel)
        self.lst_excel.setObjectName(u"lst_excel")
        self.lst_excel.setGeometry(QRect(140, 30, 61, 41))
        self.txt_excel = QLineEdit(self.tab_2)
        self.txt_excel.setObjectName(u"txt_excel")
        self.txt_excel.setGeometry(QRect(40, 30, 91, 28))
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.lbWingspan = QLabel(self.tab_3)
        self.lbWingspan.setObjectName(u"lbWingspan")
        self.lbWingspan.setGeometry(QRect(10, 30, 121, 20))
        self.txtWingspan = QLineEdit(self.tab_3)
        self.txtWingspan.setObjectName(u"txtWingspan")
        self.txtWingspan.setGeometry(QRect(140, 30, 113, 21))
        self.lbTailspan = QLabel(self.tab_3)
        self.lbTailspan.setObjectName(u"lbTailspan")
        self.lbTailspan.setGeometry(QRect(10, 60, 121, 20))
        self.txtTailspan = QLineEdit(self.tab_3)
        self.txtTailspan.setObjectName(u"txtTailspan")
        self.txtTailspan.setGeometry(QRect(140, 60, 113, 21))
        self.label_5 = QLabel(self.tab_3)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 90, 121, 20))
        self.lineEdit_5 = QLineEdit(self.tab_3)
        self.lineEdit_5.setObjectName(u"lineEdit_5")
        self.lineEdit_5.setGeometry(QRect(140, 90, 113, 21))
        self.label_6 = QLabel(self.tab_3)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 120, 121, 20))
        self.lineEdit_6 = QLineEdit(self.tab_3)
        self.lineEdit_6.setObjectName(u"lineEdit_6")
        self.lineEdit_6.setGeometry(QRect(140, 120, 113, 21))
        self.label_7 = QLabel(self.tab_3)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 150, 121, 20))
        self.lineEdit_7 = QLineEdit(self.tab_3)
        self.lineEdit_7.setObjectName(u"lineEdit_7")
        self.lineEdit_7.setGeometry(QRect(140, 150, 113, 21))
        self.label_8 = QLabel(self.tab_3)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 180, 121, 20))
        self.lineEdit_8 = QLineEdit(self.tab_3)
        self.lineEdit_8.setObjectName(u"lineEdit_8")
        self.lineEdit_8.setGeometry(QRect(140, 180, 113, 21))
        self.label_9 = QLabel(self.tab_3)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(10, 210, 121, 20))
        self.lineEdit_9 = QLineEdit(self.tab_3)
        self.lineEdit_9.setObjectName(u"lineEdit_9")
        self.lineEdit_9.setGeometry(QRect(140, 210, 113, 21))
        self.label_10 = QLabel(self.tab_3)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(10, 240, 121, 20))
        self.lineEdit_10 = QLineEdit(self.tab_3)
        self.lineEdit_10.setObjectName(u"lineEdit_10")
        self.lineEdit_10.setGeometry(QRect(140, 240, 113, 21))
        self.label_11 = QLabel(self.tab_3)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(10, 270, 121, 20))
        self.lineEdit_11 = QLineEdit(self.tab_3)
        self.lineEdit_11.setObjectName(u"lineEdit_11")
        self.lineEdit_11.setGeometry(QRect(140, 270, 113, 21))
        self.label_12 = QLabel(self.tab_3)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(10, 300, 121, 20))
        self.lineEdit_12 = QLineEdit(self.tab_3)
        self.lineEdit_12.setObjectName(u"lineEdit_12")
        self.lineEdit_12.setGeometry(QRect(140, 300, 113, 21))
        self.label_13 = QLabel(self.tab_3)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(10, 330, 121, 20))
        self.lineEdit_13 = QLineEdit(self.tab_3)
        self.lineEdit_13.setObjectName(u"lineEdit_13")
        self.lineEdit_13.setGeometry(QRect(140, 330, 113, 21))
        self.label_14 = QLabel(self.tab_3)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(10, 360, 121, 20))
        self.lineEdit_14 = QLineEdit(self.tab_3)
        self.lineEdit_14.setObjectName(u"lineEdit_14")
        self.lineEdit_14.setGeometry(QRect(140, 360, 113, 21))
        self.label_15 = QLabel(self.tab_3)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(10, 390, 121, 20))
        self.lineEdit_15 = QLineEdit(self.tab_3)
        self.lineEdit_15.setObjectName(u"lineEdit_15")
        self.lineEdit_15.setGeometry(QRect(140, 390, 113, 21))
        self.label_16 = QLabel(self.tab_3)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(10, 420, 121, 20))
        self.lineEdit_16 = QLineEdit(self.tab_3)
        self.lineEdit_16.setObjectName(u"lineEdit_16")
        self.lineEdit_16.setGeometry(QRect(140, 420, 113, 21))
        self.label_17 = QLabel(self.tab_3)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(10, 450, 121, 20))
        self.lineEdit_17 = QLineEdit(self.tab_3)
        self.lineEdit_17.setObjectName(u"lineEdit_17")
        self.lineEdit_17.setGeometry(QRect(140, 450, 113, 21))
        self.label_18 = QLabel(self.tab_3)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(10, 480, 121, 20))
        self.lineEdit_18 = QLineEdit(self.tab_3)
        self.lineEdit_18.setObjectName(u"lineEdit_18")
        self.lineEdit_18.setGeometry(QRect(140, 480, 113, 21))
        self.label_19 = QLabel(self.tab_3)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(10, 510, 121, 20))
        self.lineEdit_19 = QLineEdit(self.tab_3)
        self.lineEdit_19.setObjectName(u"lineEdit_19")
        self.lineEdit_19.setGeometry(QRect(140, 510, 113, 21))
        self.btnUpdate = QPushButton(self.tab_3)
        self.btnUpdate.setObjectName(u"btnUpdate")
        self.btnUpdate.setGeometry(QRect(660, 30, 83, 29))
        self.tabWidget.addTab(self.tab_3, "")

        self.retranslateUi(Widget)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(Widget)
    # setupUi

    def retranslateUi(self, Widget):
        Widget.setWindowTitle(QCoreApplication.translate("Widget", u"Widget", None))
        self.addButton.setText(QCoreApplication.translate("Widget", u"Add", None))
        self.textBrowser.setHtml(QCoreApplication.translate("Widget", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Segoe UI'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.label.setText(QCoreApplication.translate("Widget", u"+", None))
        self.label_2.setText(QCoreApplication.translate("Widget", u"=", None))
        self.imgPlot.setText("")
        self.btnPlot.setText(QCoreApplication.translate("Widget", u"plot", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("Widget", u"Tab 1", None))
        self.insertButton.setText(QCoreApplication.translate("Widget", u"Put text in box", None))
        self.btnVSP.setText(QCoreApplication.translate("Widget", u"Set Scale", None))

        __sortingEnabled = self.lst_excel.isSortingEnabled()
        self.lst_excel.setSortingEnabled(False)
        ___qlistwidgetitem = self.lst_excel.item(0)
        ___qlistwidgetitem.setText(QCoreApplication.translate("Widget", u"A1", None));
        ___qlistwidgetitem1 = self.lst_excel.item(1)
        ___qlistwidgetitem1.setText(QCoreApplication.translate("Widget", u"A2", None));
        ___qlistwidgetitem2 = self.lst_excel.item(2)
        ___qlistwidgetitem2.setText(QCoreApplication.translate("Widget", u"A3", None));
        ___qlistwidgetitem3 = self.lst_excel.item(3)
        ___qlistwidgetitem3.setText(QCoreApplication.translate("Widget", u"A4", None));
        self.lst_excel.setSortingEnabled(__sortingEnabled)

        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("Widget", u"Tab 2", None))
        self.lbWingspan.setText(QCoreApplication.translate("Widget", u"Wing sq ft:", None))
        self.lbTailspan.setText(QCoreApplication.translate("Widget", u"Vertical Tail sq ft:", None))
        self.label_5.setText(QCoreApplication.translate("Widget", u"Wingspan:", None))
        self.label_6.setText(QCoreApplication.translate("Widget", u"Wingspan:", None))
        self.label_7.setText(QCoreApplication.translate("Widget", u"Wingspan:", None))
        self.label_8.setText(QCoreApplication.translate("Widget", u"Wingspan:", None))
        self.label_9.setText(QCoreApplication.translate("Widget", u"Wingspan:", None))
        self.label_10.setText(QCoreApplication.translate("Widget", u"Wingspan:", None))
        self.label_11.setText(QCoreApplication.translate("Widget", u"Wingspan:", None))
        self.label_12.setText(QCoreApplication.translate("Widget", u"Wingspan:", None))
        self.label_13.setText(QCoreApplication.translate("Widget", u"Wingspan:", None))
        self.label_14.setText(QCoreApplication.translate("Widget", u"Wingspan:", None))
        self.label_15.setText(QCoreApplication.translate("Widget", u"Wingspan:", None))
        self.label_16.setText(QCoreApplication.translate("Widget", u"Wingspan:", None))
        self.label_17.setText(QCoreApplication.translate("Widget", u"Wingspan:", None))
        self.label_18.setText(QCoreApplication.translate("Widget", u"Wingspan:", None))
        self.label_19.setText(QCoreApplication.translate("Widget", u"Wingspan:", None))
        self.btnUpdate.setText(QCoreApplication.translate("Widget", u"Update", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("Widget", u"Page", None))
    # retranslateUi

